version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: open
    versions:
    - 7.3.1
    - 7.4.0
    - 7.4.1
    - 7.4.2
    - 8.0.2
    - 8.0.4
    - 8.0.5
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: yalc
    versions:
    - 1.0.0-pre.50
